# Pandas

for data analytics

In [1]:
!pip install pandas

Requirement already satisfied: pandas in /Users/him/miniconda3/lib/python3.12/site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /Users/him/miniconda3/lib/python3.12/site-packages (from pandas) (2.2.5)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/him/miniconda3/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Users/him/miniconda3/lib/python3.12/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /Users/him/miniconda3/lib/python3.12/site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /Users/him/miniconda3/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("nyc_weather.csv")

df

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
0,1/1/2016,38,23,52,30.03,10,8.0,0,5,NaN,281
1,1/2/2016,36,18,46,30.02,10,7.0,0,3,NaN,275
2,1/3/2016,40,21,47,29.86,10,8.0,0,1,NaN,277
3,1/4/2016,25,9,44,30.05,10,9.0,0,3,NaN,345
4,1/5/2016,20,-3,41,30.57,10,5.0,0,0,NaN,333
5,1/6/2016,33,4,35,30.50,10,4.0,0,0,NaN,259
6,1/7/2016,39,11,33,30.28,10,2.0,0,3,NaN,293
7,1/8/2016,39,29,64,30.20,10,4.0,0,8,NaN,79
8,1/9/2016,44,38,77,30.16,9,8.0,T,8,Rain,76
9,1/10/2016,50,46,71,29.59,4,NaN,1.8,7,Rain,109
10,1/11/2016,33,8,37,29.92,10,NaN,0,1,NaN,289
11,1/12/2016,35,15,53,29.85,10,6.0,T,4,NaN,235
12,1/13/2016,26,4,42,29.94,10,10.0,0,0,NaN,284
13,1/14/2016,30,12,47,29.95,10,5.0,T,7,NaN,266
14,1/15/2016,43,31,62,29.82,9,5.0,T,2,NaN,101
15,1/16/2016,47,37,70,29.52,8,7.0,0.24,7,Rain,340
16,1/17/2016,36,23,66,29.78,8,6.0,0.05,6,Fog-Snow,345
17,1/18/2016,25,6,53,29.83,9,12.0,T,2,Snow,293
18,1/19/2016,22,3,42,30.03,10,11.0,0,1,NaN,293
19,1/20/2016,32,15,49,30.13,10,6.0,0,2,NaN,302
20,1/21/2016,31,11,45,30.15,10,6.0,0,1,NaN,312
21,1/22/2016,26,6,41,30.21,9,NaN,0.01,3,Snow,34
22,1/23/2016,26,21,78,29.77,1,16.0,2.31,8,Fog-Snow,42
23,1/24/2016,28,11,53,29.92,8,6.0,T,3,Snow,327
24,1/25/2016,34,18,54,30.25,10,3.0,0,2,NaN,286
25,1/26/2016,43,29,56,30.03,10,7.0,0,2,NaN,244
26,1/27/2016,41,22,45,30.03,10,7.0,T,3,Rain,311
27,1/28/2016,37,20,51,29.90,10,5.0,0,1,NaN,234
28,1/29/2016,36,21,50,29.58,10,8.0,0,4,NaN,298
29,1/30/2016,34,16,46,30.01,10,7.0,0,0,NaN,257
30,1/31/2016,46,28,52,29.90,10,5.0,0,0,NaN,241

In [4]:
type(df)

pandas.core.frame.DataFrame

In [5]:
df['Temperature']

0     38
1     36
2     40
3     25
4     20
5     33
6     39
7     39
8     44
9     50
10    33
11    35
12    26
13    30
14    43
15    47
16    36
17    25
18    22
19    32
20    31
21    26
22    26
23    28
24    34
25    43
26    41
27    37
28    36
29    34
30    46
Name: Temperature, dtype: int64

In [6]:
df[['Temperature']]

    Temperature
0            38
1            36
2            40
3            25
4            20
5            33
6            39
7            39
8            44
9            50
10           33
11           35
12           26
13           30
14           43
15           47
16           36
17           25
18           22
19           32
20           31
21           26
22           26
23           28
24           34
25           43
26           41
27           37
28           36
29           34
30           46

In [7]:
type(df['Temperature'])

pandas.core.series.Series

In [8]:
df[['Temperature', 'Humidity']]

    Temperature  Humidity
0            38        52
1            36        46
2            40        47
3            25        44
4            20        41
5            33        35
6            39        33
7            39        64
8            44        77
9            50        71
10           33        37
11           35        53
12           26        42
13           30        47
14           43        62
15           47        70
16           36        66
17           25        53
18           22        42
19           32        49
20           31        45
21           26        41
22           26        78
23           28        53
24           34        54
25           43        56
26           41        45
27           37        51
28           36        50
29           34        46
30           46        52

In [9]:
type(df[['Temperature']])

pandas.core.frame.DataFrame

In [10]:
print(df['Temperature'][0])

38

In [11]:
type(df['Temperature'][0])

numpy.int64

In [12]:
df.Temperature

0     38
1     36
2     40
3     25
4     20
5     33
6     39
7     39
8     44
9     50
10    33
11    35
12    26
13    30
14    43
15    47
16    36
17    25
18    22
19    32
20    31
21    26
22    26
23    28
24    34
25    43
26    41
27    37
28    36
29    34
30    46
Name: Temperature, dtype: int64

In [13]:
df['Temperature'].max()

np.int64(50)

In [14]:
print(df['Temperature'].mean())

34.67741935483871

In [15]:
df.shape

(31, 11)

In [16]:
df.size

341

In [17]:
df.ndim

2

In [18]:
df.head()

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
0,1/1/2016,38,23,52,30.03,10,8.0,0,5,NaN,281
1,1/2/2016,36,18,46,30.02,10,7.0,0,3,NaN,275
2,1/3/2016,40,21,47,29.86,10,8.0,0,1,NaN,277
3,1/4/2016,25,9,44,30.05,10,9.0,0,3,NaN,345
4,1/5/2016,20,-3,41,30.57,10,5.0,0,0,NaN,333

In [19]:
df.columns

Index(['EST', 'Temperature', 'DewPoint', 'Humidity', 'Sea Level PressureIn',
       'VisibilityMiles', 'WindSpeedMPH', 'PrecipitationIn', 'CloudCover',
       'Events', 'WindDirDegrees'],
      dtype='object')

In [20]:
df.index

RangeIndex(start=0, stop=31, step=1)

In [21]:
df.loc[4]

EST                     1/5/2016
Temperature                   20
DewPoint                      -3
Humidity                      41
Sea Level PressureIn       30.57
VisibilityMiles               10
WindSpeedMPH                 5.0
PrecipitationIn                0
CloudCover                     0
Events                       NaN
WindDirDegrees               333
Name: 4, dtype: object

## Handling missing values

In [22]:
df = pd.read_csv('weather_data2.csv')

df

         day  temperature  windspeed   event
0   1/1/2017         32.0        6.0    Rain
1   1/4/2017          NaN        9.0   Sunny
2   1/5/2017         28.0        NaN    Snow
3   1/6/2017          NaN        7.0     NaN
4   1/7/2017         32.0        NaN    Rain
5   1/8/2017          NaN        NaN   Sunny
6   1/9/2017          NaN        NaN     NaN
7  1/10/2017         34.0        8.0  Cloudy
8  1/11/2017         40.0       12.0   Sunny

In [23]:
import numpy as np

np.nan

nan

In [ ]:
NaN = "Not a Number"

In [24]:
type(df['day'][0])

str

In [25]:
df.set_index('day', inplace=True)

df

           temperature  windspeed   event
day
1/1/2017          32.0        6.0    Rain
1/4/2017           NaN        9.0   Sunny
1/5/2017          28.0        NaN    Snow
1/6/2017           NaN        7.0     NaN
1/7/2017          32.0        NaN    Rain
1/8/2017           NaN        NaN   Sunny
1/9/2017           NaN        NaN     NaN
1/10/2017         34.0        8.0  Cloudy
1/11/2017         40.0       12.0   Sunny

### fillna

fill not available

In [26]:
new_df = df.fillna(0)

new_df

           temperature  windspeed   event
day
1/1/2017          32.0        6.0    Rain
1/4/2017           0.0        9.0   Sunny
1/5/2017          28.0        0.0    Snow
1/6/2017           0.0        7.0       0
1/7/2017          32.0        0.0    Rain
1/8/2017           0.0        0.0   Sunny
1/9/2017           0.0        0.0       0
1/10/2017         34.0        8.0  Cloudy
1/11/2017         40.0       12.0   Sunny

In [27]:
new_df = df.fillna({
    'temperature': 0,
    'windspeed': 0,
    'event': 'No Event',
})

new_df

           temperature  windspeed     event
day
1/1/2017          32.0        6.0      Rain
1/4/2017           0.0        9.0     Sunny
1/5/2017          28.0        0.0      Snow
1/6/2017           0.0        7.0  No Event
1/7/2017          32.0        0.0      Rain
1/8/2017           0.0        0.0     Sunny
1/9/2017           0.0        0.0  No Event
1/10/2017         34.0        8.0    Cloudy
1/11/2017         40.0       12.0     Sunny

In [28]:
df

           temperature  windspeed   event
day
1/1/2017          32.0        6.0    Rain
1/4/2017           NaN        9.0   Sunny
1/5/2017          28.0        NaN    Snow
1/6/2017           NaN        7.0     NaN
1/7/2017          32.0        NaN    Rain
1/8/2017           NaN        NaN   Sunny
1/9/2017           NaN        NaN     NaN
1/10/2017         34.0        8.0  Cloudy
1/11/2017         40.0       12.0   Sunny

In [29]:
## drop na


new_df = df.dropna()

new_df

           temperature  windspeed   event
day
1/1/2017          32.0        6.0    Rain
1/10/2017         34.0        8.0  Cloudy
1/11/2017         40.0       12.0   Sunny

In [30]:
df = pd.read_csv('weather_datamissing.csv')

df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017       -99999          7  Sunny
2  1/3/2017           28     -99999   Snow
3  1/4/2017       -99999          7      0
4  1/5/2017           32     -99999   Rain
5  1/6/2017           31          2  Sunny
6  1/6/2017           34          5      0

In [31]:
np.nan

nan

In [32]:
new_df = df.replace(-99999, value=np.nan)

new_df

        day  temperature  windspeed  event
0  1/1/2017         32.0        6.0   Rain
1  1/2/2017          NaN        7.0  Sunny
2  1/3/2017         28.0        NaN   Snow
3  1/4/2017          NaN        7.0      0
4  1/5/2017         32.0        NaN   Rain
5  1/6/2017         31.0        2.0  Sunny
6  1/6/2017         34.0        5.0      0

In [34]:
new_df = df.replace({
    'temperature': -99999,
    'windspeed': -99999,
    'event': '0',
}, value=np.nan)

new_df

        day  temperature  windspeed  event
0  1/1/2017         32.0        6.0   Rain
1  1/2/2017          NaN        7.0  Sunny
2  1/3/2017         28.0        NaN   Snow
3  1/4/2017          NaN        7.0    NaN
4  1/5/2017         32.0        NaN   Rain
5  1/6/2017         31.0        2.0  Sunny
6  1/6/2017         34.0        5.0    NaN

In [ ]:
0

'0'